config/routes.rb
Rails.application.routes.draw do
    root to: 'creatures#index' # same as `get "/" => "creatures#index"`
    get '/creatures', to: 'creatures#index', as: 'creatures' # same as `get "/creatures" => "creatures#index"`
    get '/creatures/new', to: 'creatures#new', as: "new_creature"
    get '/creatures/:id', to: 'creatures#show', as: "creature"
    get '/creatures/:id/edit', to: 'creatures#edit', as: "edit_creature"  
    post '/creatures', to: 'creatures#create'
    # The update route
    patch "/creatures/:id", to: "creatures#update"
    # the destroy route
    delete "/creatures/:id", to: "creatures#destroy"
end

app/models/creature.rb
class Creature < ActiveRecord::Base
	belongs_to :creature
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
		def index
            @creatures = Creature.all
            render :index
        end
        def new
            render :new
        end
        def create
            new_creature = params.require(:creature).permit(:name, :description)
            creature = Creature.create(new_creature)
            redirect_to "/creatures/#{creature.id}"
        end
        def new
            @creature = Creature.new
            render :new
        end
        def show
            id = params[:id]
            @creature = Creature.find(id)
            render :show
        end
        def edit
            id = params[:id]
            @creature = Creature.find(id)
            render :edit
        end
        def update
        creature_id = params[:id]
        creature = Creature.find(creature_id)

        # get updated data
        updated_attributes = params.require(:creature).permit(:name, :description)
        # update the creature
        creature.update_attributes(updated_attributes)

        #redirect to show
        redirect_to "/creatures/#{creature_id}"
    	end
    	def destroy
        creature_id = params[:id]
        creature = Creature.find(creature_id)
        creature.destroy
        redirect_to "/creatures"
    	end
        
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<%= link_to 'Home', creatures_path %>
<h1> We are here to edit </h1>

app/views/creatures/index.html.erb
	<div id="creatures" class="transitions-enabled">
		<% @creatures.each do |creature| %>
            <div class="box panel panel-default">
            	<img src="http://i.imgur.com/sDLIAZD.png" alt="">
            	<div class="panel-body">
			        <h3><%= creature.name %> </h3>
			        <p><%=  creature.description %></p>
			        <p><%= link_to  "View Details", creature, method: :get %> <%= button_to "Delete", creature, method: :delete %></p>
			      </div>
			</div>     
    	<% end %>
	</div>

app/views/creatures/new.html.erb
<%= link_to 'Home', creatures_path %>


<%= form_for @creature do |f| %>

    <%= f.text_field :name %>
    <%= f.text_area :description %>
    <%= f.submit "save creature" %>

<% end %>

app/views/creatures/show.html.erb
<%= link_to 'Home', creatures_path %>
<div>
    Name: <%= @creature.name %> <br>
    Description: <%=  @creature.description %>
</div>

<%= form_for @creature do |f| %>

    <%= f.text_field :name %>
    <%= f.text_area :description %>
    <%= f.submit "update creature" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>